baseURL = "http://localhost:1313/"
title = "Jane - A super concise theme for Hugo"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"

hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 3              # Number of articles displayed on the homepage # 首页每页显示的文章数
rssLimit = 20             # Limit Entry Count to Rss file # 限制 Rss 文章输出数量
disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: params.author.name ↓ # 默认为下面配置的params.author.name ↓
enableGitInfo = true      # use git commit log to generate lastmod record # 可根据 Git 中的提交生成最近更新记录。
# uglyURLs = true         # more info: https://gohugo.io/content-management/urls/#ugly-urls

[pagination]
  pagerSize = 5           # Number of articles displayed on the homepage  # 首页每页显示的文章数

# Enable author pages
#[taxonomies]
#  author = "author"
#  tag = "tags"
#  category = "categories"

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "en"           # Default language to use
[languages.en]
  languageCode = "en"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu              # 配置目录
  name = "Home"
  weight = 10
  identifier = "home"
  pageref = "/"
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  pageref = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  pageref = "/tags/"
[[menu.main]]
  name = "external-link"
  weight = 50
  pageref = "https://gohugo.io"


[params]
  debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda
  since = "2017"            # Site creation time          # 站点建立时间
  homeFullContent = false   # if false, show post summaries on home page. Otherwise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary
  mainSections = ["post"]

  author.name = "Jane"      # essential                     # 必需
  author.email = "me@example.com" # optional, for RSS             # 可选
  author.url = "/about"        # optional                      # 可选

  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle = "Jane"        # default: the title value    # 默认值: 上面设置的title值
  keywords = ["Hugo", "theme","jane"]
  description = "Hugo theme jane example site."

  # paginate of archives, tags and categories             # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值
  archive-paginate = 3

  # paginate style, default use numbered pagination links
  # if true, use original "Previous" and "Next" links.
  # paginateOriginalStyle = true

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # show word count and read time ?                       # 是否显示字数统计与阅读时间
  moreMeta = true

  # show language chooser in menu
  showMenuLanguageChooser = true

  showAuthorInfo = true # show author info below the article

  # Optional custom wallpaper image URL. Can be a remote image or local /static/img/wallpaper.jpg (make sure it has a small filesize for quick site painting)
  # wallpaper = "/static/img/wallpaper.jpg"
  wallpaper = "https://followingmyfeet.com/wp-content/uploads/2018/02/825_2229-HDR.jpg"

  # 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true                                                                            # 是否开启目录
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe            # 是否启用PhotoSwipe（图片可点击）
  bootcdn = false           # In china. @Deprecated: use [params.publicCDN]             # 是否使用bootcdn(@Deprecated: 请使用[params.publicCDN])
  mathjax = false           # see https://www.mathjax.org/                              # 是否使用mathjax（数学公式）
  katex = false             # see https://github.com/KaTeX/KaTeX
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  changyanAppid = ""        # Changyan app id             # 畅言
  changyanAppkey = ""       # Changyan app key
  tencent_analytics = ""    # Tencent Analytics
  baidu_push = false        # baidu push                  # 百度
  baidu_analytics = ""      # Baidu Analytics
  baidu_verification = ""   # Baidu Verification
  google_verification = ""  # Google_Verification         # 谷歌

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file

  # add custom info on the footer.   # 添加备案信息
  # customFooter = "京ICP备10000000号-1"

  # Remark42 is self-hosted privacy-focused comment system, https://remark42.com
  remark42Url = "https://remark42.example.com"
  remark42SiteId = "remark"

  [params.commentCount.remark42] # enable "comment count" feature for remark42, requires moreMeta param to be enabled as well
    enable = true

  [params.publicCDN]        # load these files from public cdn                          # 启用公共CDN，需自行定义
    enable = false
    gitmentJS = '<script src="https://cdn.jsdelivr.net/npm/gitment@0.0.3/dist/gitment.browser.min.js" crossorigin="anonymous"></script>'
    gitmentCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/gitment@0.0.3/style/default.min.css" crossorigin="anonymous">'
    photoswipe = '<script src="https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe.js" integrity="sha256-AC9ChpELidrhGHX23ZU53vmRdz3FhKaN9E28+BbcWBw=" crossorigin="anonymous"></script>'
    photoswipeUI = '<script src="https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe-ui-default.min.js" integrity="sha256-UKkzOn/w1mBxRmLLGrSeyB4e1xbrp4xylgAWb3M42pU=" crossorigin="anonymous"></script>'
    photoswipeCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe.css" integrity="sha256-SBLU4vv6CA6lHsZ1XyTdhyjJxCjPif/TRkjnsyGAGnE=" crossorigin="anonymous">'
    photoswipeSKIN = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/default-skin/default-skin.css" integrity="sha256-c0uckgykQ9v5k+IqViZOZKc47Jn7KQil4/MP3ySA3F8=" crossorigin="anonymous">'

  [params.giscus]         # giscus is a comment system based on GitHub Discussions. see https://giscus.app
    enable = true
    repo = "xianmin/comments-for-hugo-theme-jane"
    repoId = "MDEwOlJlcG9zaXRvcnkxNDAyNDYzNjc="
    category = "Announcements"
    categoryId = "DIC_kwDOCFv9X84CRRWF"
    # mapping = "pathname"  # comment value is the default value
    # strict = 0
    # reactionsEnabled = 1
    # emitMetadata = 0
    # inputPosition = "top"
    # theme = "light"
    # lang = "en"
    # lazyLoading = false

  [params.utteranc]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es
    enable = false
    repo = "xianmin/comments-for-hugo-theme-jane"    # The repo to store comments
    issueTerm = "pathname"

  [params.commento] # Commento is a feature rich lightweight comment system oriented on privacy (https://commento.io/)
    enable = false
    url = "http://commento.example.com"

  [params.livere]          	#LiveRe comment. see https://www.livere.com/
	  uid = ""

  # Valine.
  # You can get your appid and appkey from https://leancloud.cn
  # more info please open https://valine.js.org
  [params.valine]
    enable = false
    appId = ''
    appKey = ''
    notify = false  # If you are using valine-admin(https://github.com/DesertsP/Valine-Admin) to notify users, do NOT enable this.
    verify = false # Verification code
    avatar = 'mm'
    placeholder = ''

  [params.search.google]    # google custom search, see https://cse.google.com
    enable = false
    id = "002186711602136249422:q1gkomof_em"
    title = "Search"

  [params.reward]                                         # 文章打赏
    enable = false
    wechat = "/path/to/your/wechat-qr-code.png"           # 微信二维码
    alipay = "/path/to/your/alipay-qr-code.png"           # 支付宝二维码

  [params.counter.busuanzi]  # a Chinese visitor counter  # 不蒜子计数器
    enable = false

  [params.counter.leancloud]  # Chinese leancloud visitor counter  # leancloud 计数器
    enable = false
    appId = ""
    appKey = ""

  [params.commentCount.disqus] # show counts of comments for Disqus
    enable = false

  # use public git repo url to link lastmod git commit, enableGitInfo should be true.
  # 指定 git 仓库地址，可以生成指向最近更新的 git commit 的链接，需要将 enableGitInfo 设置成 true.
  [params.gitInfo]
    gitRepo = "https://github.com/xianmin/hugo-theme-jane"
    showCommitMessage = true

  [params.social]                                         # 社交链接
    a-email = "mailto:your@email.com"
    b-stack-overflow = "http://localhost:1313"
    c-twitter = "http://localhost:1313"
    d-facebook = "http://localhost:1313"
    e-linkedin = "http://localhost:1313"
    f-google = "http://localhost:1313"
    g-github = "http://localhost:1313"
    h-weibo = "http://localhost:1313"
    i-zhihu = "http://localhost:1313"
    j-douban = "http://localhost:1313"
    k-pocket = "http://localhost:1313"
    l-tumblr = "http://localhost:1313"
    m-instagram = "http://localhost:1313"
    n-gitlab = "http://localhost:1313"
    o-goodreads = "http://localhost:1313"
    p-coding = "http://localhost:1313"
    q-bilibili = "http://localhost:1313"
    r-codeforces = "http://localhost:1313"
    s-mastodon = "http://localhost:1313"
    t-youtube = "http://localhost:1313"
    u-twitch = "http://localhost:1313"

# jsonfeed support
# more information: https://github.com/xianmin/hugo-theme-jane/issues/23
# to have json output it's necessary to uncomment this block of code and create a index.jsonfeed.json template, using hugo template specs
# [outputs]
#   home = ["html", "jsonfeed","rss"]
#   page = ["html"]
#
# [outputFormats]
# [outputFormats.jsonfeed]
#   mediaType = "application/json"
#   baseName = "feed"
#   isPlainText = true


# multilingual support example
# [languages]
# [languages.en]
#   title = "Jane - A simple theme for Hugo"
#   weight = 1
# [languages.zh-cn]
#   title = "Jane —— 一个简洁的 Hugo 主题"
#   weight = 2


# more information https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  defaultMarkdownHandler = "goldmark"  # blackfriday or goldmark
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  # Highlight options. See https://gohugo.io/content-management/syntax-highlighting/
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noHl = false
    style = 'friendly'
    tabWidth = 4

# icons used by Jane, import module
[module]
  [[module.imports]]
    path = 'github.com/hugomods/icons/vendors/mdi'
  [[module.imports]]
    path = 'github.com/hugomods/icons/vendors/lucide'
